name: sqlite3_library_windows
description: Flutter package to bundle sqlite3 library to your windows apps
version: 2.1.0+1
repository: https://github.com/Milvintsiss/sqlite3_library_windows
homepage: https://github.com/Milvintsiss/sqlite3_library_windows
issue_tracker: https://github.com/Milvintsiss/sqlite3_library_windows/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - sqlite3.dll
